# Project information
site_name: Algorithms Quick Reference
site_description: An algorithms quick reference, ideally for use during interview perparation.
site_author: David Fair
site_url: https://airmanfair.github.io/quickreference

# Repository
repo_name: airmanfair/quickreference
repo_url: https://github.com/airmanfair/quickreference

# Configuration
theme:
  name: material
  language: en
  custom_dir: custom
  favicon: assets/favicon.png
  palette:
    primary: teal
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/globe-americas
    repo: fontawesome/brands/github

# Customization
extra:
  social:
    - icon: fontawesome/brands/github-square
      link: https://github.com/airmanfair
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/david-j-fair/